### PR TITLE
Added Description for Issue #126

### PR DESCRIPTION
**Pull request by malu254**

### CODE REVIEW

**Review by git-kick — COMMENTED** [review]
README.md already has proper comments regarding the N polling interval.

**Comment by git-kick** [comment]
no change needed:
"Polling interval long [h] | Define how often ioBroker will request state updates from E3/DC for rarely or never modified variables.
-- | --
Request tag table | Assign single request tags to S/M/L/N polling intervals. N stands for "never".
... "

**Comment by malu254** [comment]
Oh sorry, my mistake i was on a older branch

**Comment by git-kick** [comment]
No problem. So many versions... Thanks for contributing!

----------------------------------------

19.12.2022 21:01:09 malu254 ***@***.***>:

**Pull request closed without merging**
