### PR TITLE
Update index_m.html because of Issue #126

### PR DESCRIPTION
**Pull request by helper0815**

### CODE REVIEW

**Review by ka-vaNu — APPROVED** [review]

**Review by ka-vaNu — COMMENTED** [review]
Looks good

**Review by ka-vaNu — APPROVED** [review]
Looks good

**Comment by git-kick** [comment]
Thank you @helper0815 for preparing the PR. Currently, my dev environment is down due to a hardware issue. I will proccess the PR asap.

**Review by git-kick — APPROVED** [review]
Thank you and sorry for the (review) delay.

**Comment by git-kick** [comment]
will be released with v1.0.9

**Pull request closed without merging**
